// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH98ZIgc7txTr27yK08B6VOJ5i5TDh6rs',
    appId: '1:562962861141:web:ba44556466c77e6b2a98dc',
    messagingSenderId: '562962861141',
    projectId: 'orthoflex-7210d',
    authDomain: 'orthoflex-7210d.firebaseapp.com',
    databaseURL: 'https://orthoflex-7210d-default-rtdb.firebaseio.com',
    storageBucket: 'orthoflex-7210d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkdPWf4mnWVkvaaY0X2x7HPYu9pE9kivA',
    appId: '1:562962861141:android:46c921c2368edb002a98dc',
    messagingSenderId: '562962861141',
    projectId: 'orthoflex-7210d',
    databaseURL: 'https://orthoflex-7210d-default-rtdb.firebaseio.com',
    storageBucket: 'orthoflex-7210d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqQ2UaahntMNup1yrnlHo__NGiRtwFiAg',
    appId: '1:562962861141:ios:43e7204ad7979d032a98dc',
    messagingSenderId: '562962861141',
    projectId: 'orthoflex-7210d',
    databaseURL: 'https://orthoflex-7210d-default-rtdb.firebaseio.com',
    storageBucket: 'orthoflex-7210d.appspot.com',
    iosBundleId: 'com.example.orthoflexelbow',
  );
}
